### ISSUE TITLE
Mockup generated code

### ISSUE THREAD

**Issue by fbie** [tkok/MDD-E2012-P6#3]
This task is very important for our understanding of what the code generator will produce. We (together with Andrzej) need to verify that our way of implementing an ECDAR specification yields the correct behavior. This requires writing an abstract implementation of what we will generate to execute ECDAR specifications. We will then need to re-fine those until Andrzej approves.

I have set up a separate project in https://github.com/tkok/MDD-E2012-P6/tree/issue-3-mockup-generated-code called **dk.itu.ecdar.text.generator.mockup** for this.

(I know, very long project name, but at least we stay consistent with the other projects)

**Comment by Booyaches** [comment]
I got my github up and running. Can @fbie add me to this issue please?

**Comment by fbie** [comment]
Unfortunately, only one person can be added per issue, so far I have referenced people the same way you just did (e.g. @Booyaches). I don't know if there's a possibility to change this from the user-side.

**Comment by fbie** [comment]
Issue description updated. I think we need more people to work on this simultaneously.

**Comment by fbie** [comment]
Cited from http://people.cs.aau.dk/adavid/ecdar/examples.html#lang:

> To define timed I/O automata, timed game automata of TIGA with the following constraints are used:
> - Invariants may not be strict.
> - Inputs must use controllable edges.
> - Outputs must use uncontrollable edges.
> - All channels must be declared broadcast.
> - The system is implicitly input enabled due to broadcast communication but for refinement checking purposes, the relevant inputs must be explicit in the model.
> - In the case of parallel composition of several components, a given output must be exclusive to one component.
> - For implementations, outputs must be urgent.
> - For implementations, every state must have independent time progress, i.e., progress must be ensured by either >an output or infinite delay.
> - Tau transitions (no output or input) are forbidden.
> - Global variables are forbidden.

**Comment by fbie** [comment]
First version merged into master
