### ISSUE TITLE
Write simulator environment

### ISSUE THREAD

**Issue by fbie** [tkok/MDD-E2012-P6#7]
To be able to test a specification that requires input from the outside (e.g. pressing a button), we require a small simulator environment in which the code generated for the specification can run. Ideally, this environment would also log everything that happens to provide feedback.

**Comment by fbie** [comment]
@wainach  Nico, can you maybe add your Log class to the IEnvironment in some way? The branch is [https://github.com/tkok/MDD-E2012-P6/tree/issue-7-simulator-environment] Thanks!

**Comment by wainach** [comment]
@fbie Done :) See you soon...

**Comment by fbie** [comment]
First version merged into master
